//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YunZhiFaceRecoDataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public string strUserID { get; set; }
        public string strWorkCode { get; set; }
        public string strName { get; set; }
        public string strPassword { get; set; }
        public int dwOrigin { get; set; }
        public string strMobilePhone { get; set; }
        public string strTelephone { get; set; }
        public string strEmailAddress { get; set; }
        public Nullable<int> dwVerifyMode { get; set; }
        public byte[] pbIcon { get; set; }
        public Nullable<int> enumUserStatus { get; set; }
        public Nullable<System.DateTime> odtUpdateDate { get; set; }
        public Nullable<System.DateTime> odtCreateDate { get; set; }
        public string strHint { get; set; }
        public string strAttriReserved1 { get; set; }
        public string strAttriReserved2 { get; set; }
        public string strAttriReserved3 { get; set; }
        public string strAttriReserved4 { get; set; }
        public string strAttriReserved5 { get; set; }
        public string strAttriReserved6 { get; set; }
        public string strAttriReserved7 { get; set; }
        public string strAttriReserved8 { get; set; }
        public string strAttriReserved9 { get; set; }
    }
}
